# Generated by Django 4.2 on 2024-04-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_fname', models.CharField(max_length=50)),
                ('actor_lname', models.CharField(max_length=50)),
                ('actor_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_fname', models.CharField(max_length=50)),
                ('director_lname', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rating', models.FloatField(default=0, max_length=5)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_img', models.ImageField(default='/media', upload_to='images')),
                ('age_limit', models.IntegerField(max_length=5)),
                ('movie_date', models.DateField()),
                ('movie_year', models.CharField(max_length=5)),
                ('movie_country', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('description', models.CharField(max_length=250)),
                ('actor', models.ManyToManyField(related_name='movie', to='api.actor')),
                ('director', models.ManyToManyField(related_name='movie', to='api.director')),
                ('genre', models.ManyToManyField(related_name='movie', to='api.genre')),
                ('rating', models.ManyToManyField(related_name='movie', to='api.rating')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
