# Generated by Django 4.2 on 2024-04-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname_lname_of_user', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(max_length=13)),
                ('type_of_payment', models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD')], max_length=20)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(max_length=5),
        ),
    ]
